server:
  port: 8888

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
    dataspurse:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/course?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8
      username: root
      password: 111111

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*