server:
  port: 8889

logging:
  path: logs
  file: mylog.log


spring:
  application:
    name: report
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 111111

mybatis:
  type-aliases-package: com.course.com.course.model
  mapper-locations:
    - mapper/*